### Crear curso
POST http://localhost:8080/api/v1/curso-service/cursos
Content-Type: application/json

{
  "nombre": "Matemáticas Avanzadas",
  "descripcion": "Curso de nivel superior",
  "idDocente": 1,
  "duracionHoras": 60,
  "modalidad": "Presencial",
  "cuposDisponibles": 30,
  "horario": "Lunes y Miércoles 14:00-16:00",
  "idSemestre": 1,
  "numeroCreditos": 4
}

### Actualizar curso (ID en el body)
PUT http://localhost:8080/api/v1/curso-service/cursos
Content-Type: application/json

{
  "id": 1,
  "nombre": "Matemáticas Avanzadas Actualizado",
  "descripcion": "Descripción actualizada",
  "idDocente": 1,
  "duracionHoras": 64,
  "modalidad": "Híbrido",
  "cuposDisponibles": 25,
  "horario": "Lunes y Miércoles 14:00-17:00",
  "idSemestre": 1,
  "numeroCreditos": 5
}

### Eliminar curso (ID como query param)
DELETE http://localhost:8080/api/v1/curso-service/cursos?id=1

### Obtener paginado
GET http://localhost:8080/api/v1/curso-service/curso/page/0?size=5

### Cursos por semestre
GET http://localhost:8080/api/v1/curso-service/cursos/semestre/1

### Cursos por docente
GET http://localhost:8080/api/v1/curso-service/cursos/docente/1